  * Collaborating with psychologists, neuroscientists, teachers, and geoscientists on a longitudinal quasi-experiment seeking neural markers of conceptual understanding
  
    * Big picture strategizing that makes sense in practice and in theory and communicating those strategies to people at various levels of the hierarchy
  
  
  I think this paper--the example I attached--will get accepted to this person's conference, but I wanted to do a deeper dive into the data and explore secondary research questions. For survey data, it might include doing psychometrics on item-level data to help you figure out what your surveys are really measuring, structural and latent analyses (eg Structural Equation Modeling) to examine issues of causality, visualizing the data lots of ways. This kind of exploration and testing usually results in a more interesting paper that makes a more unique contribution to the literature. 


Can I post an R and R on a preprint archive? Yes!
July 18, 2019
Edit
I’m learning how to do “open science”: sharing data in public repositories, hosting reproducible workflows on github, and posting in preprint archives. I don’t know how to do a lot of this yet, and I think it will be helpful to post about my journey here.

I have been writing and rewriting this paper since before I was born (it feels like!). It has been rejected, resubmitted, reconfigured, restructured, and reanalyzed repeatedly.

BUT ! The most amazing thing has happened. During the most recent revision, my co–authors and I came up with a new way to think about the data. I’m proud of this version, and I want it to be available while it’s under review.

Before I did this process, I had the wrong idea about what “preprint” means. I had assumed it is for a paper that we would traditionally call “in press”. Actually, though, a “preprint” is any version of the paper that hasn’t yet been refereed (or is in that process). “In press” or “accepted” papers are referred to as “postprints”.

Here’s how it works:
aa
First, I had to start an OSF account (here is my currently-empty profile), which involved getting an ORC ID. I recommend ORC, because it is a unique identifier for an author…. like a doi for people. Here’s mine! OSF and ORC ID setup is a one time thing.

I don’t understand how to utilize either yet, but I’ll figure that out later.

Next, I hit up SHERPA/RoMEO. You can search for the journal and it will return their archiving policies. My paper is under review at Discourse Processes.


The results from SHERPA/RoMEO search for Discourse Processes.
Discourse Processes allows you to post preprints, postprints, but not the publisher’s pdf. So, I can post my under-review paper (“preprint”).

I decided to use the pdf generated by the publisher’s submission software. Of course, this is the internet, so you have to also manually enter all the information like the title, abstract, keywords, authors, and so on. You have to have all authors’ permission before you upload.

Here is the preprint!